CREATE TABLE AUTH_USER(
    user_id BIGSERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    profilePicture TEXT NOT NULL,
    fullname VARCHAR(255) NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE AUTH_GROUP(
    group_id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE USER_GROUP(
    user_group_id BIGSERIAL PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES AUTH_USER(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(group_id) REFERENCES AUTH_GROUP(group_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CATEGORY(
    category_id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
CREATE TABLE EXPENSE(
    expense_id BIGSERIAL PRIMARY KEY,
    expense_name TEXT NOT NULL,
    transaction_time TIMESTAMP,
    expense_thumbnail TEXT NOT NULL,
    expense_amount BIGINT NOT NULL,
    expense_information TEXT NOT NULL DEFAULT '',
    is_affecting BOOLEAN DEFAULT TRUE,
    user_id BIGINT NULL,
    group_id BIGINT NULL,
    prev_balance_id BIGINT,
    current_balance_id BIGINT,
    FOREIGN KEY(user_id) REFERENCES AUTH_USER(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(group_id) REFERENCES AUTH_GROUP(group_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE EXPENSE_CATEGORY(
    expense_category_id BIGSERIAL NOT NULL,
    category_id BIGINT NOT NULL,
    expense_id BIGINT NOT NULL,
    FOREIGN KEY(category_id) REFERENCES CATEGORY(category_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(expense_id) REFERENCES EXPENSE(expense_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE INCOME(
    income_id BIGSERIAL PRIMARY KEY,
    income_name TEXT NOT NULL,
    transaction_time TIMESTAMP,
    income_thumbnail TEXT NOT NULL,
    income_amount BIGINT NOT NULL,
    income_information TEXT NOT NULL DEFAULT '',
    is_affecting BOOLEAN DEFAULT TRUE,
    user_id BIGINT NULL,
    group_id BIGINT NULL,
    prev_balance_id BIGINT,
    current_balance_id BIGINT,
    FOREIGN KEY(user_id) REFERENCES AUTH_USER(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(group_id) REFERENCES AUTH_GROUP(group_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE INCOME_CATEGORY(
    income_category_id BIGSERIAL NOT NULL,
    category_id BIGINT NOT NULL,
    income_id BIGINT NOT NULL,
    FOREIGN KEY(category_id) REFERENCES CATEGORY(category_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(income_id) REFERENCES INCOME(income_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BALANCE(
    balance_id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NULL,
    group_id BIGINT NULL,
    related_update BOOLEAN DEFAULT TRUE,
    amount BIGINT NOT NULL DEFAULT 0,
    transaction_time TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES AUTH_USER(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(group_id) REFERENCES AUTH_GROUP(group_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BALANCE_CHAIN(
    balance_chain_id BIGSERIAL PRIMARY KEY,
    prev_balance_id BIGINT NOT NULL,
    next_balance_id BIGINT NOT NULL,
    FOREIGN KEY(prev_balance_id) REFERENCES BALANCE(balance_id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(next_balance_id) REFERENCES BALANCE(balance_id) ON UPDATE CASCADE ON DELETE CASCADE
  );
